/**
 * Create Stream API
 *
 * POST /api/streams/create - Creates a new payment stream
 *
 * Flow:
 * 1. Client generates stream ID and escrow address
 * 2. Client funds the escrow account with totalAmount + reserves
 * 3. Client calls this API with the deposit tx hash as proof
 * 4. API records the stream in the database
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import {
  createStreamWithId,
  validateStreamInput,
  calculateStreamMetrics,
  getStreamUrl,
  formatFlowRate,
} from '@/lib/streamingPayments';
import { getEscrowAddress, accountExists, getAccountBalance } from '@/lib/streamEscrow';
import { type NetworkType } from '@/lib/stellar';

export async function POST(request: NextRequest) {
  try {
    // Verify authentication
    const session = await getServerSession();
    if (!session?.user?.email) {
      return NextResponse.json(
        { error: 'Authentication required' },
        { status: 401 }
      );
    }

    const body = await request.json();
    const {
      streamId, // Pre-generated by client
      senderAddress,
      recipientAddress,
      recipientEmail,
      totalAmount,
      asset = 'XLM',
      startTime,
      durationSeconds,
      cliffSeconds,
      curveType = 'linear',
      title,
      description,
      memo,
      network = 'testnet',
      depositTxHash, // Proof of escrow funding
      escrowAddress, // Escrow address for verification
    } = body;

    // Validate required fields for funded stream
    if (!streamId) {
      return NextResponse.json(
        { error: 'Stream ID is required' },
        { status: 400 }
      );
    }

    if (!depositTxHash) {
      return NextResponse.json(
        { error: 'Deposit transaction hash is required. Please fund the escrow first.' },
        { status: 400 }
      );
    }

    // Validate input
    const validation = validateStreamInput({
      senderAddress,
      recipientAddress,
      totalAmount,
      durationSeconds,
      cliffSeconds,
      memo,
    });

    if (!validation.valid) {
      return NextResponse.json(
        { error: validation.error },
        { status: 400 }
      );
    }

    // Validate curve type
    const validCurves = ['linear', 'cliff', 'exponential', 'steps'];
    if (curveType && !validCurves.includes(curveType)) {
      return NextResponse.json(
        { error: 'Invalid curve type. Must be: linear, cliff, exponential, or steps' },
        { status: 400 }
      );
    }

    // Validate network
    if (!['testnet', 'mainnet'].includes(network)) {
      return NextResponse.json(
        { error: 'Network must be testnet or mainnet' },
        { status: 400 }
      );
    }

    // Verify escrow address matches
    const expectedEscrowAddress = getEscrowAddress(streamId, network as NetworkType);
    if (escrowAddress && escrowAddress !== expectedEscrowAddress) {
      return NextResponse.json(
        { error: 'Escrow address mismatch' },
        { status: 400 }
      );
    }

    // Verify escrow account exists and is funded
    const escrowExists = await accountExists(expectedEscrowAddress, network as NetworkType);
    if (!escrowExists) {
      return NextResponse.json(
        { error: 'Escrow account not found. Please ensure the deposit transaction was successful.' },
        { status: 400 }
      );
    }

    // Verify escrow has sufficient balance
    const escrowBalance = await getAccountBalance(expectedEscrowAddress, network as NetworkType);
    const requiredAmount = parseFloat(totalAmount);
    if (escrowBalance < requiredAmount) {
      return NextResponse.json(
        { error: `Escrow balance (${escrowBalance.toFixed(2)} XLM) is less than stream amount (${totalAmount} XLM)` },
        { status: 400 }
      );
    }

    // Create the stream with the provided ID
    const stream = await createStreamWithId({
      id: streamId,
      senderAddress,
      senderEmail: session.user.email,
      recipientAddress,
      recipientEmail,
      totalAmount,
      asset,
      startTime,
      durationSeconds,
      cliffSeconds,
      curveType,
      title,
      description,
      memo,
      network,
      depositTxHash,
    });

    // Calculate initial metrics
    const metrics = calculateStreamMetrics(stream);

    // Generate URL
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL ||
                    request.headers.get('origin') ||
                    'https://stellaray.fun';
    const streamUrl = getStreamUrl(stream.id, baseUrl);

    return NextResponse.json({
      success: true,
      stream: {
        ...stream,
        url: streamUrl,
        metrics,
        flowRateDisplay: formatFlowRate(parseFloat(stream.flowRate), stream.asset),
        escrowAddress: expectedEscrowAddress,
      },
    });
  } catch (error) {
    console.error('Error creating stream:', error);
    return NextResponse.json(
      { error: 'Failed to create payment stream' },
      { status: 500 }
    );
  }
}
